### ISSUE TITLE
SINTESIS

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-3-sintesis-Litzy-lopez4#2]
[SINTESIS_LITZY LOPEZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Litzy-lopez4/files/12515879/SINTESIS_LITZY.LOPEZ.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
